frontend:
  - changed-files:
    - any-glob-to-any-file: jobtrail-frontend/**

backend:
  - changed-files:
    - any-glob-to-any-file: jobtrail-backend/**

ci: 
  - changed-files:
    - any-glob-to-any-file: .github/workflows/**

release:
  - base-branch: "main"