import type { Metadata } from "next"
import { Roboto_Slab } from "next/font/google"
import "./globals.css"
import "@radix-ui/themes/styles.css"
import { Theme } from "@radix-ui/themes"
import { Provider } from "@/providers/Provider"

const robotoSlab = Roboto_Slab({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
    variable: "--font-roboto-slab",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <Theme>
                <body
                    className={`${robotoSlab.variable} antialiased`}
                >
                    <Provider>
                        {children}
                    </Provider>
                </body>
            </Theme>
        </html>
    )
}