name: CI

env:
  BACKEND_PATH: jobtrail-backend
  NODE_ENV: test
  TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/jobtrail_test
  JWT_SECRET: my_secret_session_token_secret
  RESEND_API_KEY: resend_api_key
  RESEND_FROM: from

on:
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
            - 6379:6379
        options: >-
            --health-cmd "redis-cli ping"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: jobtrail_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: cd ${{ env.BACKEND_PATH }} && bun ci

      - name: Migrate database
        run: cd ${{ env.BACKEND_PATH }} && bun run migrate

      - name: Run tests
        run: cd ${{ env.BACKEND_PATH }} && bun test
