name: Create Pull Request to Master

on:
    push:
        branches: ["staging"]
    workflow_dispatch:

jobs:
    create-pr-to-master:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v8.1.1
              with:
                branch: "main"
                title: "Release to Prod"