name: Frontend test

env:
  NEXT_PATH: jobtrail-frontend

on:
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: cd ${{ env.NEXT_PATH }} && bun install

      - name: Build app
        run: cd ${{ env.NEXT_PATH }} && bun run build

      - name: Test lint
        run: cd ${{ env.NEXT_PATH }} && bun lint

      - name: Install Cypress
        run: cd ${{ env.NEXT_PATH }} && npm install cypress

      - name: Run Component tests
        uses: cypress-io/github-action@v7.1.5
        with:
            working-directory: ${{ env.NEXT_PATH }}
            component: true
            browser: chrome
            install: false

      - name: Run E2E tests
        uses: cypress-io/github-action@v7.1.5
        with:
            working-directory: ${{ env.NEXT_PATH }}
            config: baseUrl=http://localhost:3000
            wait-on: http://localhost:3000
            install: false
            browser: chrome
            start: bun run start